name: cymae
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.76
  - cuda-documentation=12.0.76
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.90
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.78
  - cuda-nsight-compute=12.0.0
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.76
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.90
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.90
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.90
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - curl=7.88.1
  - dbus=1.13.18
  - expat=2.4.9
  - ffmpeg=4.3
  - fftw=3.3.9
  - fontconfig=2.14.1
  - freetype=2.12.1
  - gdbm=1.18
  - gds-tools=1.5.0.59
  - gettext=0.21.0
  - giflib=5.2.1
  - git=2.40.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcufile=1.5.0.59
  - libcufile-dev=1.5.0.59
  - libcurand=10.3.1.50
  - libcurand-dev=10.3.1.50
  - libcurl=7.88.1
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libpng=1.6.37
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - ncurses=6.3
  - nettle=3.7.3
  - nsight-compute=2022.4.0.15
  - nspr=4.33
  - nss=3.74
  - openh264=2.1.1
  - openssl=1.1.1w
  - pcre=8.45
  - pcre2=10.42
  - perl=5.34.0
  - pip=24.2
  - python=3.11.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.44.0
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==2.1.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - anyio==4.6.2.post1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==24.2.0
    - cachetools==5.5.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - cloudpickle==3.1.0
    - decorator==5.1.1
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - fcsparser==0.2.8
    - filelock==3.16.1
    - flowcytometrytools==0.5.1
    - frozenlist==1.4.1
    - fsspec==2024.10.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.35.0
    - google-auth-oauthlib==1.2.1
    - grpcio==1.67.0
    - h11==0.14.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.26.1
    - idna==3.10
    - igraph==0.11.6
    - jinja2==3.1.4
    - jiter==0.6.1
    - joblib==1.4.2
    - leidenalg==0.10.2
    - lightning==2.4.0
    - lightning-utilities==0.11.8
    - llvmlite==0.43.0
    - markdown==3.7
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - networkx==3.4.2
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - oauthlib==3.2.2
    - openai==1.52.0
    - packaging==24.1
    - pandas==2.2.3
    - patsy==0.5.6
    - phenograph==1.5.7
    - pillow==11.0.0
    - platformdirs==4.3.6
    - propcache==0.2.0
    - protobuf==5.28.2
    - psutil==6.1.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.4.1
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pynndescent==0.5.13
    - pynvml==11.5.3
    - pyqt5-sip==12.15.0
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.4.0
    - pytz==2022.7.1
    - pyyaml==6.0.2
    - regex==2024.9.11
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rsa==4.9
    - safetensors==0.4.5
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentry-sdk==2.17.0
    - setproctitle==1.3.3
    - shap==0.46.0
    - six==1.16.0
    - slicer==0.0.8
    - smmap==5.0.1
    - sniffio==1.3.1
    - statsmodels==0.14.4
    - sympy==1.13.1
    - tensorboard==2.18.0
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - texttable==1.6.7
    - threadpoolctl==3.5.0
    - timm==1.0.11
    - tokenizers==0.20.1
    - torch==2.5.0
    - torchinfo==1.8.0
    - torchmetrics==1.5.0
    - torchvision==0.20.0
    - tqdm==4.64.1
    - transformers==4.45.2
    - triton==3.1.0
    - typing-extensions==4.12.2
    - tzdata==2024.2
    - umap-learn==0.5.6
    - urllib3==2.2.3
    - wandb==0.18.5
    - werkzeug==3.0.4
    - xgboost==2.1.1
    - yarl==1.16.0
